### ISSUE TITLE
AGS: Valves

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#1]
Valves- Currently the valves reflect 10-20 inches. Cost estimating is waiting to hear back from our vendor to see if knife gate valves will be cheaper with sizes greater than 30 inches. The range for valves can be from 10 inches to 48 inches. Currently the default from 10-30 inches should be plug valves. 

[RE APD Nereda Changes .zip](https://github.com/aquaaerobic/AquaNereda/files/936145/RE.APD.Nereda.Changes.zip)

**Comment by chukon** [comment]
Please test this issue. If resolved, please close. -  Chuck

**Comment by sbainbridge** [comment]
Thank you!

**Comment by chukon** [comment]
Waiting on 30 inch to be added.
