### ISSUE TITLE
AGS: Instrumentation - Remove DO Control Checkbox 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#11]
Instrumentation: Remove DO Control Checkbox

**Comment by aglauch** [comment]
Please note that the DO probes should be auto built into the control panel's BOM

**Comment by chukon** [comment]
DO Checkbox removed from Instrumentation tab.

Please test and close.

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
Done! Thank you!
