### ISSUE TITLE
AGS: Low water level and High water level descriptions 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#13]
6.	Low water level and High water level descriptions should be changed to reflect process water level so this shows up as a min water level on the preliminary report. I can stop by your desk to discuss this change.

**Comment by chukon** [comment]
Where does this need to be changed? - Chuck

**Comment by sbainbridge** [comment]
Hi Chuck, 

This should take place in the design calcs tab of the AGS basin. 

![image](https://cloud.githubusercontent.com/assets/27778784/25969200/bdc84066-3659-11e7-981c-e11198d9ccd5.png)

Please let me know if you have questions. 

Thank you, Sophia

**Comment by chukon** [comment]
This is ready to test

**Comment by sbainbridge** [comment]
Before I close this issue. I want to discuss this screen with Manuel.

**Comment by ckonkolaqua** [comment]
ok

**Comment by bquimby** [comment]
this item is done. any other cosmetic items will be separate issues
