### ISSUE TITLE
Sludge Buffer: Add Buttons (Sludge Buffer & Pumps)

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#20]
3.	Add Buttons
o	Sludge Manifold
o	Pumps

**Comment by sbainbridge** [comment]
Hi Chuck, 

Disable, air valves, blowers, super vision, disable select equipment, opening notes, and freight on the tab in APD. 

Add influent valves .

**Comment by sbainbridge** [comment]
In addition please add units to the description in accordance with the image. 

![image](https://cloud.githubusercontent.com/assets/27778784/25487711/a27a0996-2b2a-11e7-9f1c-5b94bab93bfb.png)

**Comment by chukon** [comment]
Don't need this any longer since we are using Nereda Admin Form in Reports Menu.

**Comment by sbainbridge** [comment]
Hi Chuck, 

Can we please add the full calculations & the standard equipment group for the pumps screen like we do in the pre-eq basin? 

Currently the pumps are a button & we have to manually add in the pump. 

![image](https://cloud.githubusercontent.com/assets/27778784/26058319/04f85818-3943-11e7-8f9f-b6733031effd.png)


Would it be possible to have the pumps screen in the sludge buffer be similar to that in the pre-eq? Please see below. 

![image](https://cloud.githubusercontent.com/assets/27778784/26058361/38d37faa-3943-11e7-8e5a-77ed93ef595e.png)

Please let me know if you have any questions. 

Thank you, 

Sophia

**Comment by chukon** [comment]
Question: I need the calculations for the pump screen to populate the fields. below is the calcs for SBR Pumps:
![2017-05-15_0804](https://cloud.githubusercontent.com/assets/3256516/26058879/5a0e1566-3945-11e7-8f38-b00d209cdff3.png)

**Comment by sbainbridge** [comment]
Waiting on Ali to provide Chuck with flows and heads. 

The following is the standard for Sludge buffer pumps:
-	Gorman Rupp external (most likely these pumps will be 3 – 20 HP)
-	If we decide to add a progressive cavity pump, the standard will be Netzsch pump (these will have to be quoted)

**Comment by sbainbridge** [comment]
@aliciagroen 

Hi Ali, any word on this?

**Comment by aliciagroen** [comment]
@sbainbridge I added the info under #33, I didn't know about this #.

**Comment by ckonkolaqua** [comment]
Thanks
