### ISSUE TITLE
Controls: Check OutPut

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#21]
Controls: Check OutPut

**Comment by sbainbridge** [comment]
We need to bring a work order upstairs and ask Ali to look this over. I will do this today.

**Comment by sbainbridge** [comment]
Hi Chuck, 

I looked this over with Cost Estimating and we both agree on the parts and quantities that the group is pulling in.

One item that we will want to talk about in tomorrow's meeting is the analog output module (part # 2702282?) and adding this as a standard part in the control panel. From there AEs will change the quantities based on how many VFD's we require for the blowers and pumps.

**Comment by chukon** [comment]
Please test Controls AutoBuild (See Attached)
![2017-04-26_1015](https://cloud.githubusercontent.com/assets/3256516/25442015/78e43654-2a69-11e7-8fbb-5fea68d0e1f1.png)

**Comment by sbainbridge** [comment]
Hi Chuck, 

As we talked about yesterday please make the default panel 1,000 plus because this will most likely be standard for a 3-4 basin design. 

In addition, please add the analog output card.

**Comment by chukon** [comment]
Please restart APD Dev, test and close. - Chuck

Test Design 147372

**Comment by chukon** [comment]
Please test

**Comment by bquimby** [comment]
Could you please add part #2702282 (Analog Output Module) to the control panel autobuild? quantity can be 1 for now and we will manually change it for the time being. However, we will need 1 of these modules per 8 vfds in the system. 

We would like to consider a separate item for changing the "#Mini-CAS Pumps" box in the Controls tab to "Number of VFDs" and have the autobuild use this to calculate the number of these output modules based on that value.

**Comment by bquimby** [comment]
Have confirmed that VFD input box is present and #2702282 is added to control panel autobuild. However, regardless of input into VFD box, the quantity of #2702282 in the BOM is always "1." Also noticed that tabbing or clicking away from the VFD input box resets it to 0... might be that the value is not getting saved.
