### ISSUE TITLE
Report: Admin Page

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#25]
Admin Page for Prelim Report

**Comment by chukon** [comment]
[Admin Page Example (From DTN).pdf](https://github.com/aquaaerobic/AquaNereda/files/968096/Admin.Page.Example.From.DTN.pdf)

**Comment by chukon** [comment]
Aaron, please attach Excel Spreadsheet from Admin Page Example

**Comment by chukon** [comment]
Test Admin Report Screens to see if data holds.

**Comment by chukon** [comment]
If data holds in "Admin Report Screen" then Nereda Preliminary report will be updated so data source for basin values will come from Admin Report Screens. Chuck

**Comment by chukon** [comment]
Prelim Report has been tied into Admin Report data. Design Duplication has integrated Admin Report data as well.

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
Hi Chuck, 

Please see the attachment with comments regarding the preliminary report. 

[2017-05-15 SunPaper AquaNeredaPreliminaryReport.pdf](https://github.com/aquaaerobic/AquaNereda/files/1002226/2017-05-15.SunPaper.AquaNeredaPreliminaryReport.pdf)

**Comment by chukon** [comment]
Sludge buffer now displaying

**Comment by ckonkolaqua** [comment]
Please test & close is complete.

**Comment by bquimby** [comment]
Looks like this is fixed. Other issue I put up regarding sludge buffer also looks fixed, so I will close that as well.
