### ISSUE TITLE
Report: Order of Equipment

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#28]
e.	Order of Equipment

**Comment by chukon** [comment]
ready to test

**Comment by sbainbridge** [comment]
Hi Chuck, 
Please correct the title to say Water Level Correction Tank
![image](https://cloud.githubusercontent.com/assets/27778784/25394818/b4cf1e4c-29a4-11e7-93cd-970348efc7fb.png)
Please omit the word manifold.
![image](https://cloud.githubusercontent.com/assets/27778784/25394802/a88525f0-29a4-11e7-955d-e62833813924.png)

Please have the controls build in after the other equipment just like we do in an SBR. Also please correct the text to say Controls w/ Starters


![image](https://cloud.githubusercontent.com/assets/27778784/25395000/496d0280-29a5-11e7-98be-2e19b0d5ac0e.png)

**Comment by sbainbridge** [comment]
There are also some instrumentation descriptions that need to be deleted and I will talk to Ali about this.

**Comment by chukon** [comment]
Please test equipment order in Prelim design report along with above issues. If you have equipment for that area in the BOM manually delete before autobuilding.

**Comment by sbainbridge** [comment]
Hi Chuck, 

We are getting there! I believe that the order of tanks is being built correctly :) However the equipment within each tank is being built out of order.  In addition, there are some issues with the fonts, underlines.

This equipment list below is what we are striving to achieve (this is the same equipment design example that Manuel sent in an email to you): 
![image](https://cloud.githubusercontent.com/assets/27778784/25488099/c24daaa6-2b2b-11e7-8eef-8baa72d4cbb7.png)

![image](https://cloud.githubusercontent.com/assets/27778784/25488114/cbe00b4a-2b2b-11e7-9561-fe4af14780c4.png)

![image](https://cloud.githubusercontent.com/assets/27778784/25488128/d887c1ee-2b2b-11e7-8559-0a569491988f.png)

Currently this is what the equipment list looks like: 

![image](https://cloud.githubusercontent.com/assets/27778784/25488167/f90ef6b2-2b2b-11e7-864f-6843b5e63194.png)

![image](https://cloud.githubusercontent.com/assets/27778784/25488182/01a119cc-2b2c-11e7-85d9-2fc8fd35cfb5.png)
![image](https://cloud.githubusercontent.com/assets/27778784/25488196/0a222bae-2b2c-11e7-8222-c33304669876.png)

**Comment by chukon** [comment]
Please restart and check equipment order in PreLim report. If ok, close issues. If not. markup report and let me know exactly what is out of order. The equipment order is driven by Equipment Category number which at this point could be difficult to do since the equipment caregory numbers are in ALL part groups in which cost estimating has added.

**Comment by aglauch** [comment]
Brett is working on a design currently, and should be back in the office tomorrow morning.  I'll ask him to review this with his current design.

**Comment by bquimby** [comment]
Basin order in the BOM (and on reports) appears to be ok, and issue with controls section appears to be fixed. Equipment order for pre-EQ, post-EQ is ok. I can't seem to get sludge buffer basin working right now, so couldn't check this.

Equipment order for the AGS reactors still needs to be adjusted. Current order of groups in BOM is:

1. influent valve
2. diffusers
3. blowers
4. air valves
5. level sensors
6. instrumentation
7. influent distribution
8. effluent weir
9. sludge removal


Order should be:

1. influent valve
2. influent distribution
3. effluent weir
4. sludge removal
5. diffusers
6. blowers
7. air valves
8. level sensors
9. instrumentation

Also note that the opening line description for the influent distribution (manifold) group should read "Influent Distribution Assembly(ies) consisting of:" replacing the word "manifold" with "distribution."

**Comment by ckonkolaqua** [comment]
Thanks @bquimby

**Comment by chukon** [comment]
Brett, the equipment order has been modified. Please Restasrt APD Dev, Test and close.

**Comment by chukon** [comment]
Brett, ready to test. Restart APD Dev,create new design, add equipment, run prelim report

![2017-05-04_1209](https://cloud.githubusercontent.com/assets/3256516/25715889/b247f872-30c2-11e7-9d67-5b452eafcaee.png)

**Comment by chukon** [comment]
Please test

**Comment by sbainbridge** [comment]
Hi Chuck! We are almost there! The order of equipment is almost complete. 

Can we please have the engineering for each tank show up in the BOM Prior to the PLC controls group? 

The engineering order should follow: 

Engineering- AquaNereda PreEQ 
Engineering - AquaNereda
Engineering - Water Level Correction Tank 
Engineering- Post - Eq
Engineering - Sludge Buffer
Engineering - Digester

**Comment by chukon** [comment]
This has been updated. Please test in APD Dev and APD Live

**Comment by bquimby** [comment]
![neredafix](https://cloud.githubusercontent.com/assets/27785862/26110297/8b094f0a-3a17-11e7-95dd-64b26990f5f6.png)

Chuck,
Could we move the engineering and freight groups around as shown in the above image? We would like to have the equipment for each basin come first, then controls, then engineering groups, then supervision/freight in that order on the BOM as is in SBR designs.

All other issues (equipment order, order of the engineering groups themselves) appear to be fixed.

Thank you!

**Comment by chukon** [comment]
@bquimby this is ready to test

**Comment by bquimby** [comment]
this has been fixed. thank you!
