### ISSUE TITLE
Controls: Equipment Edits

### ISSUE THREAD

**Issue by aglauch** [aquaaerobic/AquaNereda#29]
[2017-04-26 Control Panel APD Edits.pdf](https://github.com/aquaaerobic/AquaNereda/files/959351/2017-04-26.Control.Panel.APD.Edits.pdf)

Please make the following changes to the control panel:
1) See picture for edits to the input page.
2) Change part# D2711P-T7C4D8 to 2752361.  2752361 should always be pulled in, regardless of the number of basins.

**Comment by chukon** [comment]
Changed part# D2711P-T7C4D8 to 2752361

Please restart APD Dev, test and close issue. Chuck

**Comment by sbainbridge** [comment]
Hi Chuck, 

The second part of Aaron's request is correct and complete.

Please see the 2017-04-26 Control Panel APD Edits.pdf attachment above and edit the controls page. Once this is done I believe we can close this item.

**Comment by chukon** [comment]
@aglauch Does VFD replace Mini-Cas label or an additional section for VFD?

**Comment by aglauch** [comment]
Chuck, VFD should be in addition to the Mini-CAS, not replacing.

**Comment by ckonkolaqua** [comment]
Thanks

**Comment by chukon** [comment]
@aglauch Is this a number field?

**Comment by chukon** [comment]
@aglauch This is ready to test

**Comment by bquimby** [comment]
this appears to be working
