### ISSUE TITLE
WLC: Buttons

### ISSUE THREAD

**Issue by aglauch** [aquaaerobic/AquaNereda#30]
[2017-04-26 WLC APD Edits.pdf](https://github.com/aquaaerobic/AquaNereda/files/959395/2017-04-26.WLC.APD.Edits.pdf)

Please make the following changes to the Water Level Correction Tank Equipment Tab:

1) Remove PreEQ Opening Notes, DDM Mixer Calcs, PreEQ Closing Notes, & Aeration Selection options.
2) Please note that all of these should still be available if the system is a "Pre-EQ Basin" instead of a "WLC"

**Comment by chukon** [comment]
Please restart APD Dev, test and close issue. - Chuck

test design 147372

**Comment by sbainbridge** [comment]
Hi Chuck, 

Thank you for removing the PreEQ Opening Notes, DDM Mixer Calcs, PreEQ Closing Notes, & Aeration Selection options in the water level correction tank. 

Please note that the pre-equalization tank should be able to select AGS opening notes, mixer, and closing notes. Currently we are not able to select these in the pre-eq (see screen shot below). Please allow AE's to select these options. 


![image](https://cloud.githubusercontent.com/assets/27778784/25823951/45b578e4-3403-11e7-9381-0afba4ac7db9.png)

**Comment by chukon** [comment]
PreEQ Opening Notes, DDM Mixer Calcs, PreEQ Closing Notes, & Aeration  now available or PreEQ

**Comment by sbainbridge** [comment]
Thank you! This is fixed.
