### ISSUE TITLE
ALL: Opening/Closing Notes

### ISSUE THREAD

**Issue by aglauch** [aquaaerobic/AquaNereda#31]
Please remove opening and closing notes from all basins in the BOM.  These should not show up in the BOM by default.

**Comment by chukon** [comment]
Notes do NOT show up in BOM unless added in Equipment tabs of Basin. We do not want to remove the Opening and Closing buttons from all basins do we?

**Comment by aglauch** [comment]
[2017-05-02 Main Page APD Edits.pdf](https://github.com/aquaaerobic/AquaNereda/files/972041/2017-05-02.Main.Page.APD.Edits.pdf)

The only Opening/Closing Notes buttons that we require are the one's shown on the main page (see attached).  The remainder can be hidden from view.

**Comment by ckonkolaqua** [comment]
Aaron, 
Because these buttons are needed in all other types of installations I won't be able to remove from view but will disable from being checked. This has been done for AGS, PreEQ/WLCT, PostEQ,Sludge Buffer and Digester. Please test and close issue. Thanks, Chuck

**Comment by chukon** [comment]
Please restart APD Dev, test and close. - Chuck

**Comment by chukon** [comment]
Please test

**Comment by bquimby** [comment]
This appears to be fixed.
