### ISSUE TITLE
Digester - Updated Requirements

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#32]
Thanks Chuck,

Please see my notes below.

For the digester only:
1.       When AquaNereda Digester is selected, the equipment should remain labelled “AquaNereda”
2.       The following equipment should still show up, the same as it does in the standard SBR configuration:
a.       DDM Mixer Calcs (in lieu of the Effluent Weir Assembly)
b.      Coarse Bubble Diffusers
c.       AquaJet Aerator
d.      OxyMix Aerator
e.      Digester Opening/Closing Notes (in lieu of AGS Opening/Closing Notes)

Kind regards,
Aaron Glauch, EI
Project Application Engineer

**Comment by chukon** [comment]
Ready to test

**Comment by aglauch** [comment]
Thanks Chuck, everything seems good with this.
