### ISSUE TITLE
Autobuild Smaller Pumps in APD 

### ISSUE THREAD

**Issue by sbainbridge** [aquaaerobic/AquaNereda#33]
With smaller flows ~2 MGD or below we might need to select smaller pumps in the pre-eq. Currently we are able to manually add these pumps to the BOM however we are not able to build a standard group. 

Please write the code so these smaller pumps can be added as a standard group into APD. 

An example of an error is below. 

![image](https://cloud.githubusercontent.com/assets/27778784/26057655/2a33158a-3940-11e7-93d1-1919fc4fd162.png)
 
Please let me know if you have any questions. 

Thank you, 

Sophia

**Comment by chukon** [comment]
@sbainbridge I have updated pump list in APD. Please test. I attached below the list of all available Nereda Pumps and it looks like we don't have any 2HP and maybe we don't need any. I will invite Alicia to this bug as well.

[Nereda Pumps.xlsx](https://github.com/aquaaerobic/AquaNereda/files/1011376/Nereda.Pumps.xlsx)

**Comment by chukon** [comment]
@aliciagroen I just need the new pump Assembly numbers. Call me and I will walk up and show you how to use the bug system.

**Comment by aliciagroen** [comment]
@sbainbridge - I didn't put the 2HP pumps on the Nereda side, but I can add them if you think they will be needed.

@chukon 
[Pump.xlsx](https://github.com/aquaaerobic/AquaNereda/files/1019157/Pump.xlsx)
This is the updated pump spreadsheet with flows to use for selection, I highligheted the new pumps.

Assembly Numbers (If you are incorporating these pumps into the SBR selection they would use the same assembly number just wihout the NE)
T2 3HP - PUMP3HPT2A60 NE
T2 5HP - PUMP5HPT2A60 NE
T2 7.5HP - PUMP7.5HPT2A60 NE
T3 7.5HP - PUMP7.5HPT3A60 NE
T3 10HP - PUMP10HPT3A60 NE
T3 14HP - PUMP15HPT3A60 NE
T4 7.5HP - PUMP7.5HPT4A60 NE
T4 15HP - PUMP15HPT4A60 NE
T4 20HP - PUMP20HPT4A60 NE
T6 15HP - PUMP15HPT6A60 NE
T6 20HP - PUMP20HPT6A60 NE
T6 25HP - PUMP25HPT6A60 NE
T6 30HP - PUMP30HPT6A60 NE

**Comment by ckonkolaqua** [comment]
Thanks @aliciagroen :1st_place_medal:

**Comment by bquimby** [comment]
looks like this is working

**Comment by sbainbridge** [comment]
Hi Chuck, 

I looks like I am unable to build a 7.5 HP pump in the post eq even after you added this pump to the group. 

![image](https://user-images.githubusercontent.com/27778784/27587164-e7f18fb8-5b08-11e7-94fb-eba940f3cf2e.png)

**Comment by chukon** [comment]
Latest pumps are now added. Please test.

**Comment by bquimby** [comment]
This appears to be fixed.
