### ISSUE TITLE
Sludge Buffer Solids Removal System 

### ISSUE THREAD

**Issue by sbainbridge** [aquaaerobic/AquaNereda#34]
Hi Chuck, 

The Nereda SOLIDS Manifold assembly should be built as a standard into the BOM for the AquaNereda Sludge Removal System in the Sludge Buffer. This is made out of cheap plastic and will sit on the floor. 

Currently the Sludge buffer is pulling in the Nereda SLUDGE manifold and this is not correct. 

Ali has built the group in APD for the solids manifold for the sludge buffer. I believe all that needs to be changed is the code so it pulls in the right group. 

Please let me know of i you have any questions. 

Thank you,

Sophia 
[RE_ Sludge Buffer APD Changes.pdf](https://github.com/aquaaerobic/AquaNereda/files/1001593/RE_.Sludge.Buffer.APD.Changes.pdf)

**Comment by chukon** [comment]
This has been updated. Please test in APD Dev

**Comment by bquimby** [comment]
this is fixed.
