### ISSUE TITLE
Pre-EQ pumps showing up in WLC group

### ISSUE THREAD

**Issue by bquimby** [aquaaerobic/AquaNereda#35]
![neredafix2](https://cloud.githubusercontent.com/assets/27785862/26111760/9d093c7a-3a1b-11e7-80d3-9f3bdc5169b0.png)

Chuck,
One other item I almost overlooked: when using a Pre-EQ instead of a WLC, the pre-EQ pumps show up both in the pre-EQ group (as expected) and another set of the same pump is put into a WLC group that shouldn't be there.

**Comment by chukon** [comment]
This has been fixed. Please test.

**Comment by sbainbridge** [comment]
Thank you!
