### ISSUE TITLE
Reports: Design Notes

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#39]

**Comment by sbainbridge** [comment]
Hi Chuck, 

Please find the design notes to be updated. Please update the yellow highlighted notes. Please update note 93 (freeoboard note) and add it to the standard group of AGS notes. 

[2017-06-07 AquaNereda Design Notes.xlsx](https://github.com/aquaaerobic/AquaNereda/files/1058939/2017-06-07.AquaNereda.Design.Notes.xlsx)

**Comment by bquimby** [comment]
pretty sure these are done, and there is another separate issue open with the latest design notes edits.
