### ISSUE TITLE
AGS: Lock data FFB Diffusers 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#4]
In addition we have found that the FFB diffusers and aerzen blowers will drop out of the BOM when we return the diffuser screen and have to change some paratmeters such as water level, alpha, aeration time etc. This is a major issue because this can b
[RE APD Nereda Changes .zip](https://github.com/aquaaerobic/AquaNereda/files/936167/RE.APD.Nereda.Changes.zip)
e easily missed and incorrect pricing can be sent out.

**Comment by chukon** [comment]
Please test and close

**Comment by sbainbridge** [comment]
Thank you!
