### ISSUE TITLE
Remove warning on Retrievable Fine Bubble Diffuser on Form load

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#46]
Chuck this warning showed without me doing anything yet just went to that tab.
 
![untitled](https://cloud.githubusercontent.com/assets/3256516/26678883/49be7010-4698-11e7-8755-ddb2965633af.png)

**Comment by chukon** [comment]
@tatimazzei this is a test comment. For practice, reply with "Got it". Thanks, @ckonkolaqua

**Comment by tatimazzei** [comment]
got it!

**Comment by ckonkolaqua** [comment]
Ok, good job!

**Comment by bquimby** [comment]
Is there anything left to do for this item, or can we take it off?
