### ISSUE TITLE
Preliminary Report 

### ISSUE THREAD

**Issue by sbainbridge** [aquaaerobic/AquaNereda#48]
Hi Chuck, 

Please find attached the PDF edits we need to make each time before we send out a design to an engineer. If possible please fix these items highlighted in the attached design. These highlights are inconsistencies that are not being printed correctly from the admin page to the Adobe report. 

[Preliminary Report Edits.pdf](https://github.com/aquaaerobic/AquaNereda/files/1058908/Preliminary.Report.Edits.pdf)

**Comment by bquimby** [comment]
Most of the issues in Sophia's PDF have been resolved. However, I found a few additional thing that we would like to fix. Please see the attached pdf and screenshot for details.

[prelim proposal-design summary edits.pdf](https://github.com/aquaaerobic/AquaNereda/files/1092210/prelim.proposal-design.summary.edits.pdf)
![admin rep1](https://user-images.githubusercontent.com/27785862/27395583-dddf2c52-5675-11e7-973d-335d7790cb59.png)

**Comment by chukon** [comment]
[AASI (1.1.0) DTN 2.3 (TEMPLATE).xlsx](https://github.com/aquaaerobic/AquaNereda/files/1113331/AASI.1.1.0.DTN.2.3.TEMPLATE.xlsx)
