### ISSUE TITLE
Post-EQ Diffusers/Blowers not in AquaNereda group

### ISSUE THREAD

**Issue by bquimby** [aquaaerobic/AquaNereda#49]
Diffusers and blowers for AquaNereda post-EQ are showing up under the AquaSBR post EQ group. Pumps, level sensors, and engineering for post-EQ are all where they should be.

![apd post-eq issue](https://user-images.githubusercontent.com/27785862/27334199-1f738dc2-558e-11e7-8d2f-f4e97af34829.png)

**Comment by ckonkolaqua** [comment]
I just tested and it built under Aqua Nereda PostEq.

Chuck

**Comment by ckonkolaqua** [comment]
I will look into

**Comment by bquimby** [comment]
Just confirmed that this is working fine in another design. This may have been a one-time bug. Will keep an eye out for it in the future.
