### ISSUE TITLE
Updated Design Notes for Nereda 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#50]
Hi Chuck, 

Please find attached the design note spreadsheet (2017-06-21). We have updated two notes. #17 & #18 (highlighted in green). 

Please have these changes be standard for each Nereda design note group. 

Thank you,

Sophia Bainbridge
Application Engineer
[2017-06-21 AquaNereda Design Notes.xlsx](https://github.com/aquaaerobic/AquaNereda/files/1091744/2017-06-21.AquaNereda.Design.Notes.xlsx)

**Comment by chukon** [comment]
Hi Chuck, 

Brett brought another note to my attention that needs a grammar fix. Can you also please fix the FOG note (highlighted in Green)?

Thank you,

Sophia Bainbridge
Application Engineer

AQUA-AEROBIC SYSTEMS, INC.
6306 N. Alpine Rd.
Loves Park, IL 61111-7655
Ph: 815-639-4523 Fax: 815-654-8258
Email: sbainbridge@aqua-aerobic.com 
www.aqua-aerobic.com

[2017-06-21 AquaNereda Design Notes 1.xlsx](https://github.com/aquaaerobic/AquaNereda/files/1091747/2017-06-21.AquaNereda.Design.Notes.1.xlsx)

**Comment by chukon** [comment]
Notes have been updated. Please test

**Comment by chukon** [comment]
Design Note Number Correction: On Excel 17 should be 461 and 18 should be 463. This has been corrected.
![2017-06-28_1318](https://user-images.githubusercontent.com/3256516/27653384-7e1e89ea-5c04-11e7-82a5-6984743a1358.png)

**Comment by bquimby** [comment]
Notes 17 and 18 are still being pulled in with the AquaNereda group. Please remove those notes from the group.

**Comment by bquimby** [comment]
Fixed!
