### ISSUE TITLE
Post-EQ: Equipment Edits

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#6]
Post-eq
Please add the same equipment in the post-eq as there is in the SBR post-eq. Please note that there is not an effluent weir in the post-eq. 
[RE APD Nereda Changes .zip](https://github.com/aquaaerobic/AquaNereda/files/936186/RE.APD.Nereda.Changes.zip)

**Comment by chukon** [comment]
@sbainbridge ready to test

**Comment by bquimby** [comment]
All of the necessary equipment appears to be present and working. This is fixed.
