### ISSUE TITLE
1) Cover Sheet + Prlim Footers

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#64]

**Comment by chukon** [comment]
The

**Comment by chukon** [comment]
**Ready to test**
[1152018_728_57_150662_PreliminaryProposal.pdf](https://github.com/aquaaerobic/AquaNereda/files/1631756/1152018_728_57_150662_PreliminaryProposal.pdf)

**Comment by chukon** [comment]
Ready to test: Cover Sheet + Prlim Footers (Nereda)

- Fix page 2 footer of Cover Sheet + Preliminary Report

- Page 2 was not showing footer information

1152018_728_57_150662_PreliminaryProposal.pdf

**Comment by sbainbridge** [comment]
This appears to be fixed.
