### ISSUE TITLE
2) Scheduling: Delete or Z-out  people who does not work at AASI

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#66]
For those who works on schedule, this creates a shorter list to search through to schedule a task.Earlier this Summer was lookend into it but it seems this wasn’t a real big deal, but it just wasn’t completed.

**Comment by chukon** [comment]
We are not able to delete any of the employees that do not work at Aqua due to projects that employee name was assigned to. However, we can sort the list to where those not actively working at Aqua show up at the bottom of the list.

**Comment by chukon** [comment]
Scheduling: Delete or Z-out people who does not work at AASI
This is ready to test. 
The list now sorts active employee to the top of the list.

**Comment by tatimazzei** [comment]
Hi Chuck,

I tried to test this, but I did not see anybody been Z-out in the scheduling. This task I believe is not ready to be test, Please confirm status.

Thank you

**Comment by chukon** [comment]
![image](https://user-images.githubusercontent.com/3256516/35150820-79b05978-fce1-11e7-87c2-195911a2f48b.png)
