### ISSUE TITLE
Sludge Buffer

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#7]
Sludge Buffer:
We do not need aeration in the sludge buffer. Please note that for sludge buffer we chose to use this basin as a “place holder basin” in lieu of a digester. We would like two more buttons created for “ sludge manifold” and “pumps.” Please note on the preliminary equipment list report this sludge manifold should read “sludge removal assembly” and not use the word manifold. 
[RE APD Nereda Changes .zip](https://github.com/aquaaerobic/AquaNereda/files/936188/RE.APD.Nereda.Changes.zip)

**Comment by chukon** [comment]
The aeration buttons are disabled in Sludge Buffer and the two buttons, sludge manifold and pumps have been added. - Chuck

`Please restart APD Dev, Test and close.`

**Comment by sbainbridge** [comment]
Thank you, Chuck! This looks great!
