### ISSUE TITLE
Material Burden on Nereda Fees in Cost 

### ISSUE THREAD

**Issue by sbainbridge** [aquaaerobic/AquaNereda#71]
The material burden for the Nereda fees should not be included as a default.

**Comment by chukon** [comment]
I will update this at Next nightly refresh.

**Comment by sbainbridge** [comment]
Thank you!

**Comment by ckonkolaqua** [comment]
[cid:image001.jpg@01D39A69.008F20E0]

**Comment by chukon** [comment]
![2018-01-31_0754](https://user-images.githubusercontent.com/3256516/35626842-94028024-065c-11e8-953e-026b0aa55b59.png)
