### ISSUE TITLE
AGS: The quantity of Nereda fees

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNereda#8]
The quantity of Nereda fees are defaulting to the number of Nereda reactors as seen below in this test design. The quantity of Nereda fees should always be one because the fee takes into account the number of reactors. Cost estimating relayed to me that this is a fix IT can do.  Can you please add this to the list of Issues on Git Hub?

**Comment by chukon** [comment]
Nereda Fees quantity is now defaulting to 1.

Please test and close.

**Comment by sbainbridge** [comment]
Looks good to me! Thank you!
